### ISSUE TITLE
Add documentation for running tests

### ISSUE THREAD

**Issue by singingwolfboy** [FSX/misaka#27]
It's *really* difficult to run the unit tests of this project. How to run the tests should be included in the documentation; ideally, it should be as easy as `python setup.py test`. (See the [setuptools docs](http://packages.python.org/distribute/setuptools.html#test-build-package-and-run-a-unittest-suite).)

**Comment by singingwolfboy** [comment]
@FSX: can you point out what you changed? I don't know if you closed this issue because you fixed the issue, or because you decided not to do it. I don't see anything in the documentation about how to run tests.

**Comment by FSX** [comment]
I still need to write the documentation for version 2.0, which will include docs about running tests.

You can already use `python setup.py test` to run the tests in 2.0. :)

**Comment by FSX** [comment]
It's done: http://misaka.61924.nl/index.html#tests
