### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by samuelcolvin** [FSX/misaka#44]
First of all there's an error in the first example in the README: `print md('some text')` should be `print md.render('some text')`.

~~Secondly, the currently releases (both `v2.0.0b1.post2` and `v1.0.2`) are in some weird state where they can't be searched for in pypi and (rather more importantly) can't be installed in certain situations, eg. on circleci.~~

Is there any plan for a proper new release of misaka?

(by the way, great package, thank you)

**update**: problem with installing on circle ci was simple requirements files being weird (in the terminal `misaka==v2.0.0b1.post2` works, but in a requirements file it needs to be `misaka==2.0.0b1.post2`) either way the a new release and consistently updated documentation would be great.

**Comment by FSX** [comment]
Thanks for reporting.

I still need to complete the documentation. That's the only thing left to do.

**Comment by FSX** [comment]
Done.

**Comment by sprin** [comment]
Congratulations and thank you! Just updated from the beta to 2.0 in [pg-discuss](https://pg-discuss.readthedocs.org/en/latest/), a comment backend.
