### ISSUE TITLE
GFM how to

### ISSUE THREAD

**Issue by samuelcolvin** [FSX/misaka#45]
GFM (github flavoured markdown) is very popular these days. It would be great if there was some help somewhere on how to get misaka to generate GFM. 

I know it's never going to be identical but some pointers for the most important features would be useful.

Currently my solution to get something close to GFM's linebreak behavior is:

``` python
def markdown(md_str):
    render = HtmlRenderer()
    md = Markdown(render, extensions=misaka.EXT_NO_INTRA_EMPHASIS)
    md_str = re.sub(r'(?<!  )\n(?!\n)(?=.)', '  \n', md_str)
    return md.render(md_str)
```

The regular expression is required since gfm does:

```
"first sentence\nsecond sentence" --> "<p>first sentence<br />second sentence"
```

Whereas hoedown and misaka require two spaces before the `\n` to insert the `<br />`. I tried overwriting most of the render methods but couldn't find a solution to the above.

There are probably other differences (particularly on tables) but newlines are most people's first stumbling block with markdown.

(updated to regex to use lookahead/behinds properly).

**Comment by samuelcolvin** [comment]
looks like [this](https://gist.github.com/fyears/5097469) might be useful too, but it used the old version of misaka and therefore `EXT_LAX_HTML_BLOCKS` which doesn't exist for version 2.x.

**Comment by FSX** [comment]
Goodmorning Samuel, I'll take a look at it.

**Comment by FSX** [comment]
`EXT_LAX_HTML_BLOCKS` is not available in Hoedown, the parser that Misaka uses. You can use `HTML_HARD_WRAP` to insert `<br>` on each linebreak.

**Comment by samuelcolvin** [comment]
I had realised that `EXT_LAX_HTML_BLOCKS` wasn't available, that's why I was looking for a better solution.

Thanks for pointing out `HTML_HARD_WRAP`, very useful.
