### ISSUE TITLE
pip3 install misaka fails to install with uninformative error 

### ISSUE THREAD

**Issue by haxwithaxe** [FSX/misaka#50]
This is more of a feature request than a bug. If nothing else this might show up on google for people with the same problem.
When installing misaka with pip on debian stretch/sid lack of libffi-dev manifests as a very long line of exceptions caught while handling other exceptions with the following message on each, burying the cause which is clearly stated before the chain of exceptions caught while handling exceptions.

```
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by FSX** [comment]
I'll add it to the documentation and also look into prebuilt packages.

Thanks for reporting.

**Comment by FSX** [comment]
Added to docs. Will close on next release.

**Comment by xrlin** [comment]
I encounter this problem when use pip in centos6.5 too.  Your post helps me. 
Thanks.
