### ISSUE TITLE
python3.5.1 can't install the misaka

### ISSUE THREAD

**Issue by magician333** [FSX/misaka#54]
I use "pip install misaka",then it will make mistakes
,like these
by the way:I use termux on android and other python package can install
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-fli5nnnd/misaka

**Comment by FSX** [comment]
I've never tested Misaka on Android. I'll try taking a look at it this week. :)

**Comment by magician333** [comment]
OK，thanks

**Comment by magician333** [comment]
FSK,are you deal with it?

**Comment by FSX** [comment]
Looking at it now.

**Comment by aidenzou** [comment]
我也遇到同样的问题
环境：Mac Python 3.5
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bh/gb96wv6s0sd81bk_pxjpbp2c0000gn/T/pip-build-b_8womsc/misaka/

**Comment by FSX** [comment]
@magician333, I get a different error. Can you send me the complete error message?

Same for @aidenzou.

**Comment by magician333** [comment]
@FSX is here , https://db.tt/OlMOanDd

**Comment by FSX** [comment]
Did you install libffi and libffi-dev?

**Comment by magician333** [comment]
@FSK no,I'will try to it

**Comment by magician333** [comment]
@FSK no,still mistake

**Comment by FSX** [comment]
Ok, please keep posting the error messages. I'll try to figure it out too.
