### ISSUE TITLE
one HtmlTocRenderer question

### ISSUE THREAD

**Issue by windism** [FSX/misaka#58]
The contents of the document are as follows：

> # shadowsocks-libev
> 
> ```bash
> # Debian / Ubuntu
> sudo apt-get install --no-install-recommends build-essential autoconf libtool libssl-dev libpcre3-dev asciidoc xmlto
> # CentOS / Fedora / RHEL
> sudo yum install gcc autoconf libtool automake make zlib-devel openssl-devel asciidoc xmlto
> ./configure && make
> sudo make install

```

` print(misaka.Markdown(misaka.HtmlTocRenderer(2))(text))`

> <ul>
> <li>
> <a href="#toc_0">shadowsocks-libev</a>
> </li>
> <li>
> <a href="#toc_1">Debian / Ubuntu</a>
> </li>
> <li>
> <a href="#toc_2">CentOS / Fedora / RHEL</a>
> </li>
> </ul>

Comments in this code block are also interpreted as headings。
How do I solve？
Thanks for your misaka

**Comment by FSX** [comment]
You need to enable the fenced codeblocks extension for the TOC renderer too.
