### ISSUE TITLE
Built-in XSS protection

### ISSUE THREAD

**Issue by Changaco** [FSX/misaka#59]
In Misaka 1.0 there was a `SAFELINK` flag that provided a decent protection against XSS attacks, but it seems to have disappeared from upstream (<https://github.com/hoedown/hoedown/issues/209>).

Misaka 2.0 could fill the gap by providing a renderer subclass with custom `autolink`, `image`, and `link` methods that check URLs. Here's the one I've written: [markdown.py](https://github.com/liberapay/liberapay.com/blob/157/liberapay/utils/markdown.py). If I submit a Pull Request to integrate that class into Misaka, will you merge it?

**Comment by FSX** [comment]
Yes, but only if you include tests. ;)

**Comment by FSX** [comment]
The PR has been merged. Thanks! :)
