### ISSUE TITLE
Customize HtmlTocRenderer anchor link

### ISSUE THREAD

**Issue by ghost** [FSX/misaka#63]
Hello

I am trying to customize the output of the HtmlTocRenderer

I wish to replace this output:
```html
<ul>
    <li><a href="#toc_0">My article</a> </li>
</ul>
``` 

By this one:
```html
<ul>
    <li><a href="#my-article">My article</a> </li>
</ul>
``` 

It is possible to do this by inheriting **HtmlTocRenderer**, or have to write another function for that ?

**Comment by FSX** [comment]
Yes, you if you set the header-callback in the renderer.

See: http://misaka.61924.nl/#misaka.BaseRenderer.header
