### ISSUE TITLE
Math is not rendering for me (using Flask-Misaka)

### ISSUE THREAD

**Issue by E-Wagner** [FSX/misaka#71]
I'm creating a blog that requires mathematics notation. The following won't render the latex notation into mathematics notation:

```
import misaka
with open('./misaka/sampletext.md', 'r') as f:
        content=f.read()  

html = misaka.html(content, extensions = misaka.EXT_MATH)
print(html)
```
(indentation is correct, github isn't showing it correctly.)
Can you help me to get this to work?
Thank you for your time

**Comment by FSX** [comment]
Misaka doesn't actually render LaTeX to math symbols.

You need [MathJax][1] or [KaTeX][2] for that.

[1]: https://www.mathjax.org/
[2]: https://katex.org/

**Comment by E-Wagner** [comment]
@FSX, thanks frank, you can close it. I got it to work with MathJax 💃

**Comment by FSX** [comment]
np :+1:

**Comment by noisytoken** [comment]
@FSX so what's the point of `EXT_MATH` and `EXT_MATH_EXPLICIT` extensions?

**Comment by FSX** [comment]
Anything between `$…$`, `$$…$$`, `\(…\)`, and `\[…\]` is not interpreted as Markdown.
