### ISSUE TITLE
Newline not rendered

### ISSUE THREAD

**Issue by huajianjiang** [FSX/misaka#76]

**Comment by FSX** [comment]
Hi, can you give some more details about what you're expecting?

**Comment by huajianjiang** [comment]
**Original:**
```
## How are arguments passed – by reference or by value?
Question part：
- item 1
- item 2
```
**Rendered**
```
<h2 id="toc_5">How are arguments passed – by reference or by value?</h2>
<p>Question part：<br>
- item 1<br>
- item 2</p>
```
If you not newline after 'Question part' , it rendered as a whole p tag, but most of other markdown render not force to newline before list or some other block. 
I don't known why? 
Thanks.

**Comment by FSX** [comment]
I'm sorry. I don't really know why. It hasn't been a problem for me so far.

I'm working on a new version of Misaka that uses md4c. That might solve your problem.
