### ISSUE TITLE
Incorrect Rendering of TOC

### ISSUE THREAD

**Issue by noisytoken** [FSX/misaka#81]
Considee the following code:

https://pastebin.com/mVHV6keK

It generates the following incorrect markup

```html
<ul>
<li>
<a href="#toc_0">H1</a>
<ul>
<li>
<a href="#toc_1">H2</a>
</li>
</ul>
</li>
<li>
<a href="#toc_2">a comment</a>
</li>
</ul>
```

The text `a comment` is part of the fenced code block. Hence, it shouldn't be part of the TOC.

**Comment by FSX** [comment]
You need to enable the fenced code block extension. Otherwise headers from fenced code blocks are also included in the TOC.
